# Site
repository: https://github.com/C4TBrilliantThoughts/resume
# favicon: images/favicon.ico

# Personal info
name: Sumanth Sanathi
title: |
  Senior Product Automation Engineer | Full Stack Developer(Web, UX/UI)
company: |
 SLK Software Services PVT LTD under the Dimension Labs Product Team.
description: sumanth's CV
favicon: /images/profile.jpg
email: c4t.brilliantthoughts@gmail.com
phone: (+91)8660422303
website: www.c4tbt.com

# Social links
twitter_username: sumanthc4t
github_username:  c4tbrilliantthoughts
dribbble_username: c4tbt
# facebook_username: 
# flickr_username: 
instagram_username: sumanth_c4t
linkedin_username: c4tbt
# pinterest_username: 
# youtube_username: 
# googleplus_username:

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sumanth and I'm a Full Stack developer (current role).I also have experience with design automation frameworks for internal product testing tools. Using Selenium, Python and Java for different of app types Web, Mobile(appium) and Desktop(Winium, AutoIT and sikuli). I have experience with my current role gaining good teamwork and leadership skills.

  I am most skilled in: Design and development of hardware and software products.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
  
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
