# Site
repository: https://github.com/C4TBrilliantThoughts/resume
# favicon: images/favicon.ico

# Personal info
name: Sumanth Sanathi
title: Senior Automation Engineer | Full Stack Developer(Web, UX/UI)
description: sumanth's CV
favicon: /images/profile.jpg
email: c4t.brilliantthoughts@gmail.com
website: www.c4tbt.com

# Social links
twitter_username: sumanthc4t
github_username:  c4tbrilliantthoughts
dribbble_username: c4tbt
# facebook_username: 
# flickr_username: 
instagram_username: sumanth_c4t
linkedin_username: c4tbt
c4t_brilliantthoughts: 
# pinterest_username: 
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
  
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
